import {
  AiMicIcon,
  AirportIcon,
  BalanceScaleIcon,
  BankIcon,
  BeachIcon,
  Bus01Icon,
  ChurchIcon,
  ComputerDesk02Icon,
  DepartementIcon,
  Dumbbell02Icon,
  EquipmentGym03Icon,
  FerryBoatIcon,
  FootballPitchIcon,
  GivePillIcon,
  Globe02Icon,
  GolfBallIcon,
  GolfHoleIcon,
  Hospital02Icon,
  HospitalBed02Icon,
  Hotel02Icon,
  House02Icon,
  Leaf01Icon,
  PartyIcon,
  PoliceStationIcon,
} from "@hugeicons/core-free-icons";
import { Place } from "../_schemas";

export const DEFAULT_PLACES_VALUES: Partial<Place> = {
  name: "",
  description: "",
  address: "",
  landmarks: "",
  city: "",
  state: "",
  country: "",
  longitude: undefined,
  latitude: undefined,
  placeType: "HOTEL",
  emails: [],
  phoneNumbers: [],
  status: "PUBLISHED",
  coverImage: undefined,
  environmentalSafetyPolicy: undefined,
  privacyPolicy: undefined,
  disclaimers: undefined,
  ownershipDocument: undefined,
  ownershipVideo: undefined,
  operatingHours: {
    schedule: [
      {
        day: "Monday",
        isOpen: true,
        openingTime: "08:00",
        closingTime: "18:00",
      },
      {
        day: "Tuesday",
        isOpen: true,
        openingTime: "08:00",
        closingTime: "18:00",
      },
      {
        day: "Wednesday",
        isOpen: true,
        openingTime: "08:00",
        closingTime: "18:00",
      },
      {
        day: "Thursday",
        isOpen: true,
        openingTime: "08:00",
        closingTime: "18:00",
      },
      {
        day: "Friday",
        isOpen: true,
        openingTime: "08:00",
        closingTime: "18:00",
      },
      {
        day: "Saturday",
        isOpen: false,
        openingTime: "08:00",
        closingTime: "18:00",
      },
      {
        day: "Sunday",
        isOpen: false,
        openingTime: "08:00",
        closingTime: "18:00",
      },
    ],
    holidays: [],
  },
};

export const PLACE_TYPES = [
  { label: "Hotel", value: "HOTEL", icon: Hotel02Icon },
  { label: "Short Let", value: "SHORT_LET", icon: DepartementIcon },
  { label: "Beach Resort", value: "BEACH_RESORT", icon: BeachIcon },
  // {
  //   label: "Recreation Center",
  //   value: "RECREATION_CENTER",
  //   icon: DepartementIcon,
  // },
  { label: "Business Hub", value: "BUSINESS_HUB", icon: ComputerDesk02Icon },
  { label: "Stadium", value: "STADIUM", icon: FootballPitchIcon },
  { label: "Sport Facility", value: "SPORT_FACILITY", icon: Dumbbell02Icon },
  { label: "Country Club", value: "COUNTRY_CLUB", icon: GolfHoleIcon },
  {
    label: "Sport Recreation Club",
    value: "SPORT_RECREATION_CLUB",
    icon: GolfBallIcon,
  },
  { label: "Hospital", value: "HOSPITAL", icon: Hospital02Icon },
  { label: "Clinic", value: "CLINIC", icon: HospitalBed02Icon },
  { label: "Pharmacy", value: "PHARMACY", icon: GivePillIcon },
  {
    label: "Spa Wellness Center",
    value: "SPA_WELLNESS_CENTER",
    icon: Leaf01Icon,
  },
  { label: "Gym", value: "GYM", icon: EquipmentGym03Icon },
  { label: "Studio", value: "STUDIO", icon: AiMicIcon },
  { label: "Airport", value: "AIRPORT", icon: AirportIcon },
  { label: "Rail Station", value: "RAIL_STATION", icon: Dumbbell02Icon },
  {
    label: "Road Transport Hub",
    value: "ROAD_TRANSPORT_HUB",
    icon: Bus01Icon,
  },
  {
    label: "Water Transport Hub",
    value: "WATER_TRANSPORT_HUB",
    icon: FerryBoatIcon,
  },
  {
    label: "Religious Centre",
    value: "RELIGIOUS_CENTRE",
    icon: ChurchIcon,
  },
  { label: "Police Station", value: "POLICE_STATION", icon: PoliceStationIcon },
  { label: "Court", value: "COURT", icon: BalanceScaleIcon },
  {
    label: "Military Barracks",
    value: "MILITARY_BARRACKS",
    icon: House02Icon,
  },
  { label: "Bank", value: "BANK", icon: BankIcon },
  { label: "Strip Club", value: "STRIP_CLUB", icon: PartyIcon },
  { label: "Other", value: "OTHER", icon: Globe02Icon },
];
